language: ruby
rvm: 
  - 2.7.1

script:
 - bundle config set deployment 'true'
 — bundle install --jobs=3 --retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

dist: trusty