language: ruby
cache:
- bundler
before_install:
- gem install bundler
before_script:
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: freight-train-2-railsville

  on:
    repo: george-bit/acebook-freight-train-to-railsville
