language: ruby
rvm:
  - 2.7.
services:
  - postgresql

before_script:
  - cp config/database.yml

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
